In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
sns.set_style(style="darkgrid")

In [3]:
def count_rows(df):
    return df.shape[0]

In [4]:
random.seed(2023)
df = pd.DataFrame(np.array([
    [random.randint(1, 5), random.randint(0, 1), random.randint(0,1)] for i in range(30)
]), columns=["cieplo", "zachmurzenie", "pada"])

df["wyjde_na_spacer"] = [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1]

In [5]:
df

    cieplo  zachmurzenie  pada  wyjde_na_spacer
0        4             1     1                1
1        3             1     0                0
2        1             1     1                0
3        2             0     0                0
4        1             0     1                0
5        1             0     0                0
6        2             0     1                0
7        4             1     0                1
8        1             1     1                0
9        1             0     0                0
10       5             0     0                1
11       1             0     1                0
12       4             0     0                1
13       5             0     1                1
14       3             0     0                1
15       3             1     0                0
16       3             0     1                0
17       5             1     1                1
18       3             1     0                1
19       2             1     0                0
20       3             0     0                1
21       5             1     0                1
22       1             1     0                0
23       1             1     0                0
24       2             0     1                0
25       4             0     1                1
26       4             1     0                1
27       3             1     0                1
28       1             1     1                0
29       4             0     1                1

In [10]:
def predict_with_bayes(
    new_row, 
    train_set=df):
    #  podzia≈Ç datasetu na dwa mniejsze zalezne od klasy
    class_zero = df[df.iloc[:, -1]==0]
    class_one = df[df.iloc[:, -1]==1]

    #  wyznaczenie prawdopodobienstwa poczatkowego 
    apriori_zero = count_rows(class_zero) / count_rows(df)
    apriori_one = count_rows(class_one) / count_rows(df)
    
    #  duze pi, czyli mnozenie w petli prawdopodobienstw
    for i, feature in enumerate(new_row):
        apriori_zero *= (class_zero.iloc[:, i] == feature).sum() / count_rows(class_zero)
        apriori_one *= (class_one.iloc[:, i] == feature).sum() / count_rows(class_one)
        
    print(f"Probability of class=0: {apriori_zero}\nProbability of class=1: {apriori_one}\nPrediction: class={0 if apriori_zero > apriori_one else 1}")

In [11]:
predict_with_bayes([5, 0, 0], train_set=df)

Probability of class=0: 0.0
Probability of class=1: 0.04285714285714286
Prediction: class=1

In [12]:
predict_with_bayes([1, 1, 1], train_set=df)

Probability of class=0: 0.075
Probability of class=1: 0.0
Prediction: class=0

In [13]:
predict_with_bayes([3, 1, 0], train_set=df)

Probability of class=0: 0.025
Probability of class=1: 0.04285714285714286
Prediction: class=1

In [14]:
predict_with_bayes([4, 0, 1], train_set=df)

Probability of class=0: 0.0
Probability of class=1: 0.03571428571428571
Prediction: class=1